; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:4d_systems_esp32s3_gen4_r8n16]
platform = espressif32
board = 4d_systems_esp32s3_gen4_r8n16
framework = arduino
;board_build.partitions = huge_app.csv
;board_build.partitions = default_16MB_8MB.csv
board_build.psram = enabled
board_build.flash_size = 16MB
board_build.mcu = esp32s3
board_build.variant = esp32s3
board_build.arduino.memory_type = qio_opi     ; Ví dụ: qio (cho flash) _opi (cho PSRAM)
;board_build.f_cpu = 240000000L
;board_build.filesystem = littlefs
board_build.filesystem = spiffs
build_flags = 
	-DESP32
  	-DCONFIG_IDF_TARGET_ESP32S3
	-I include
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
    -D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps = 
	lvgl/lvgl@^9.2.2	
	;esphome/ESPAsyncTCP-esphome@^2.0.0
	moononournation/GFX Library for Arduino@^1.5.9
    https://github.com/AudunKodehode/JC3248W535EN-Touch-LCD
    ;https://github.com/fdivitto/FabGL.git
	https://github.com/moononournation/arduino-nofrendo.git
	https://github.com/moononournation/Dev_Device_Pins.git
	https://github.com/mmMicky/TouchLib.git